#!/bin/bash
#--------------------------------------------
# 🚀 Hyperf Watch Scripts
# 🚗 Make Happy to Coding
# 👉 快乐的热更新工具，监听文件变化自动重启Hyperf
# Author: hanicc@qq.com
# Version: 20190730@beta2
# GitHub: https://github.com/ha-ni-cc/hyperf-watch
#--------------------------------------------

# 监听目录
DIR=./
# 程序文件路径
BIN=./bin/hyperf.php
# 日志文件路径
LOG=./runtime/watch.log
# fswatch命令路径
WATCH=fswatch
# 指令第一个变量
CMD=$1

#检查fswatch扩展存不存在
command -v ${WATCH} >/dev/null 2>&1 || { echo >&2 "[x] 请先安装fswatch扩展"; exit 1;}

if [[ ${CMD} = "-c" ]]
    then
    rm ${LOG}
    echo -e "🐵 Clean ${LOG} success!"
fi

ps -ef | grep php\ ${BIN}\ start | grep -v grep | awk '{print $2}' | xargs kill

echo -e "🚀 Start @ $(date "+%Y-%m-%d %H:%M:%S")"
echo -e "\n ================ \n 🚀 Start @ $(date "+%Y-%m-%d %H:%M:%S")\n ================ \n" >> ./runtime/watch.log

nohup php ${BIN} start >> ${LOG} &

${WATCH} ${DIR} | while read file
do
    EXT=${file##*.}
    if [[ ${EXT} = "php" || ${EXT} = "env" ]]
       then
       ps -ef | grep php\ ${BIN}\ start | grep -v grep | awk '{print $2}' | xargs kill
       echo -e "\n ================ \n 🔄 Restart @ $(date "+%Y-%m-%d %H:%M:%S")\n 👉 ${file} was modified\n ================ \n" >> ./runtime/watch.log
       nohup php ${BIN} start >> ${LOG} &
       echo "🔄 Restart @ $(date "+%Y-%m-%d %H:%M:%S")"
     fi
done

cat ${LOG}
